name: Build PostmarketOS Images

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pmbootstrap
        run: |
          git clone https://gitlab.com/postmarketOS/pmbootstrap.git
          cd pmbootstrap
          pip3 install .
          pmbootstrap --version
