name: Build PostmarketOS Images

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pmbootstrap
        run: |
          git clone https://gitlab.postmarketos.org/postmarketOS/pmbootstrap $HOME/pmbootstrap
          cd $HOME/pmbootstrap
          pip3 install --user .

      - name: copy pmbootstrap config 
        run: |
         cp $GITHUB_WORKSPACE/.github/workflows/pmbootstrap_v3.cfg $HOME/.config/pmbootstrap_v3.cfg

      - name: copy pmbootstrap config 
        run: |
         pmbootstrap install
